### ISSUE TITLE
Duplicate items

### ISSUE THREAD

**Issue by fisheggg** [GeWu-Lab/awesome-audiovisual-learning#4]
Hi,

Thanks for maintaining this list! I learned a lot from the listed papers 😇 
I found this paper listed twice in the Audio-visual representation learning section:

[CVPR-2023] [Vision Transformers are Parameter-Efficient Audio-Visual Learners](https://arxiv.org/abs/2212.07983)
Authors: Yan-Bo Lin, Yi-Lin Sung, Jie Lei, Mohit Bansal, Gedas Bertasius
Institution: The University of North Carolina at Chapel Hill

Best,
Arthur

**Comment by echo0409** [comment]
Hi,

We have deleted the duplicate items. Thanks a lot for your help!
